version: '3'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:6.5.0
    environment:
      - cluster.name=history-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - esnet
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200     #for kibana
      - 9300:9300

  kibana:
    container_name: kibana
    image: kibana:6.5.0
    networks:
      - esnet
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

networks:
  esnet: